=== arunabha212/Payment-Management-System/payment xml/paymentschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/paymentschema" 
xmlns:tns="http://www.example.org/paymentschema" 
elementFormDefault="qualified">

<complexType name="order-list">
	<sequence>
		<element name="order-items" type="tns:items" minOccurs="1" maxOccurs="unbounded"></element>
	</sequence>
</complexType>
<complexType name="items">
	<sequence>
		<element name="details" type="string"></element>
		<element name="quantity" type="integer"></element>
		<element name="price" type="tns:amount"></element>
		<element name="payment-status" type="tns:paystring"></element>
		<element name="duration" type="integer"></element>
		<element name="date" type="date"></element>
	</sequence>
	<attribute name="item-id" type="ID" use="required"></attribute>
</complexType>
<simpleType name="paystring">
	<restriction base="string">
		<pattern value="pending|success"/>
	</restriction>
</simpleType>
<simpleType name="amount">
	<restriction base="integer">
		<minInclusive value="0"></minInclusive>
	</restriction>
</simpleType>
<element name="global" type="tns:order-list"></element>
</schema>

=== arunabha212/Payment-Management-System/payment xml/payment.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="paymentxsl.xsl"?>
<tns:global xmlns:tns="http://www.example.org/paymentschema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/paymentschema paymentschema.xsd ">
 <tns:order-items item-id="id0">
    <tns:details>Consultation Fees</tns:details>
    <tns:quantity>1</tns:quantity>
    <tns:price>15</tns:price>
    <tns:payment-status>pending</tns:payment-status>
    <tns:duration>2</tns:duration>
    <tns:date>2021-05-22</tns:date>
  </tns:order-items>
  
  <tns:order-items item-id="id1">
    <tns:details>Elite_Subcription</tns:details>
    <tns:quantity>1</tns:quantity>
    <tns:price>299</tns:price>
    <tns:payment-status>pending</tns:payment-status>
    <tns:duration>365</tns:duration>
    <tns:date>2022-01-04</tns:date>
  </tns:order-items>
  
  <tns:order-items item-id="id2">
    <tns:details>Standard Subscription for E-course</tns:details>
    <tns:quantity>1</tns:quantity>
    <tns:price>99</tns:price>
    <tns:payment-status>success</tns:payment-status>
    <tns:duration>45</tns:duration>
    <tns:date>2021-06-18</tns:date>
  </tns:order-items>
  
  <tns:order-items item-id="id3">
    <tns:details>Consultation Fees</tns:details>
    <tns:quantity>1</tns:quantity>
    <tns:price>150</tns:price>
    <tns:payment-status>pending</tns:payment-status>
    <tns:duration>5</tns:duration>
    <tns:date>2022-02-07</tns:date>
  </tns:order-items>
  
  <tns:order-items item-id="id4">
    <tns:details>Consultation Fees</tns:details>
    <tns:quantity>1</tns:quantity>
    <tns:price>15</tns:price>
    <tns:payment-status>pending</tns:payment-status>
    <tns:duration>45</tns:duration>
    <tns:date>2021-08-26</tns:date>
  </tns:order-items>
  
  <tns:order-items item-id="id5">
    <tns:details>Mind Map 2022 </tns:details>
    <tns:quantity>1</tns:quantity>
    <tns:price>49</tns:price>
    <tns:payment-status>pending</tns:payment-status>
    <tns:duration>180</tns:duration>
    <tns:date>2021-12-12</tns:date>
  </tns:order-items>
  
  <tns:order-items item-id="id6">
    <tns:details>Consultation Fees</tns:details>
    <tns:quantity>1</tns:quantity>
    <tns:price>15</tns:price>
    <tns:payment-status>pending</tns:payment-status>
    <tns:duration>1</tns:duration>
    <tns:date>2022-05-15</tns:date>
  </tns:order-items>
  
  <tns:order-items item-id="id7">
    <tns:details> E Resources</tns:details>
    <tns:quantity>1</tns:quantity>
    <tns:price>150</tns:price>
    <tns:payment-status>pending</tns:payment-status>
    <tns:duration>365</tns:duration>
    <tns:date>2022-01-01</tns:date>
  </tns:order-items>
  
</tns:global>
